
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: time
spec:
  selector:
    matchLabels:
      app: time
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: time
    spec:
      containers:
        - name:  time
          image: localhost:5000/time
          ports:
            - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name:  time
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: time